[package]
name = "fin"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = "0.4"
clap = { version = "4", features = [ "derive", "env" ] }
colored = "2"
csv = "1"
env_logger = "0.11"
home = "0.5"
log = "0.4"
serde = { version = "1", features = [ "derive" ] }

[dev-dependencies]
tempfile = "3"
